import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SideNav from "@/components/SideNav";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import BottomNav from "@/components/BottomNav";
import React from "react";
import { getLoggedInUser } from "@/lib/action/user.action";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const user:User | undefined = await getLoggedInUser();

    if (!user) {
      redirect('/sign-in');
    }

    return (
    <div lang="en">
        <div className={inter.className}>
          <div className="flex min-h-screen overflow-x-hidden">
            <SideNav user={user} />
            {children}
          </div>
          <BottomNav user={user} />
        </div>
    </div>
    );
}